In [2]:
# import the necessary packages
import numpy as np
import imutils
import cv2
# load the input image and show its dimensions, keeping in mind that
# images are represented as a multi-dimensional NumPy array with
# shape no. rows (height) x no. columns (width) x no. channels (depth)

In [3]:

image = cv2.imread("img/cat.jpg")
(h, w, d) = image.shape
print("width={}, height={}, depth={}".format(w, h, d))
# display the image to our screen -- we will need to click the window
# open by OpenCV and press a key on our keyboard to continue execution
cv2.imshow("Image", image)
cv2.waitKey(0)

width=800, height=800, depth=3


-1

In [6]:
print(image)

[[[186 186 186]
  [186 186 186]
  [186 186 186]
  ...
  [ 23  55  91]
  [ 23  55  91]
  [ 23  55  91]]

 [[186 186 186]
  [186 186 186]
  [186 186 186]
  ...
  [ 23  55  91]
  [ 23  55  91]
  [ 23  55  91]]

 [[186 186 186]
  [186 186 186]
  [186 186 186]
  ...
  [ 21  55  91]
  [ 21  55  91]
  [ 21  55  91]]

 ...

 [[ 85  88  92]
  [ 86  89  93]
  [ 86  89  93]
  ...
  [ 98 101 105]
  [ 99 102 106]
  [100 103 107]]

 [[ 85  88  92]
  [ 86  89  93]
  [ 86  89  93]
  ...
  [ 98 101 105]
  [ 99 102 106]
  [100 103 107]]

 [[ 85  88  92]
  [ 85  88  92]
  [ 86  89  93]
  ...
  [ 98 101 105]
  [ 99 102 106]
  [100 103 107]]]


In [4]:

# convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray", gray)
cv2.waitKey(0)

-1

In [5]:
edged = cv2.Canny(gray, 30, 150)
cv2.imshow("Edged", edged)
cv2.waitKey(0)

-1

In [7]:
roi = image[60:160, 320:420]
cv2.imshow("ROI", roi)
cv2.waitKey(0)

-1

In [4]:
rotated = imutils.rotate_bound(image, 45)
cv2.imshow("Rotate", rotated)
cv2.waitKey(0)

-1

In [5]:
output = image.copy()
cv2.rectangle(output, (320, 60), (420, 160), (0, 0, 255), 2)
cv2.imshow("Rectangle", output)
cv2.waitKey(0)

-1

In [7]:
cat2 = cv2.imread("img/cat2.jpg")
cv2.imshow("Cat2",cat2)
cv2.waitKey(0)

-1

In [10]:
im1 = cv2.imread("img/subtract1.png")
im2 = cv2.imread("img/subtract2.png")
added = cv2.addWeighted(im1,0.5,im2,0.5,0)
cv2.imshow("Added",added)
cv2.waitKey(0)

-1

In [12]:
im1 = cv2.imread("img/subtract1.png")
im2 = cv2.imread("img/subtract2.png")
subtracted = cv2.subtract(im2,im1)
cv2.imshow("Subtracted",subtracted)
cv2.waitKey(0)

-1

In [15]:
im1_grey = cv2.cvtColor(im1, cv2.COLOR_BGR2GRAY)
im2_grey = cv2.cvtColor(im2, cv2.COLOR_BGR2GRAY)
ret, thr = cv2.threshold(im1_grey,100,255,cv2.THRESH_BINARY)
cv2.imshow("Thresholded",thr)
cv2.waitKey(0)

-1

In [21]:
thr = cv2.adaptiveThreshold(im1_grey,120,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY,51,2)
cv2.imshow("Thresholded",thr)
cv2.waitKey(0)

-1

In [28]:
lena = cv2.imread("img/lena_noise.png")
kernel = np.ones((3,3),np.uint8)
cv2.imshow("Erosion",cv2.dilate(lena,kernel))
cv2.waitKey(0)

-1

In [35]:
lena = cv2.imread("img/lena_noise.png")
kernel = np.ones((5,5),np.uint8)
cv2.imshow("Opening",cv2.morphologyEx(lena,cv2.MORPH_TOPHAT,kernel))
cv2.waitKey(0)

-1

In [45]:
from matplotlib import pyplot as plt
img = cv2.imread("img/dark_text.png")
laplacian = cv2.Laplacian(img,cv2.CV_64F)
sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=11)
sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=11)
cv2.imshow("Opening",laplacian)
cv2.waitKey(0)

-1

In [47]:
tetris = cv2.imread("img/tetris.png")
edges = cv2.Canny(tetris,100,200)
ret = edges
cv2.imshow("Ret",ret)
cv2.waitKey(0)

-1

In [1]:
thresh = cv2.threshold(cv2.cvtColor(tetris,cv2.COLOR_BGR2GRAY), 225, 255, cv2.THRESH_BINARY_INV)[1]

cnts = cv2.findContours(thresh, cv2.RETR_EXTERNAL,
	cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
output = tetris.copy()
# loop over the contours
for c in cnts:
	# draw each contour on the output image with a 3px thick purple
	# outline, then display the output contours one at a time
	cv2.drawContours(output, [c], -1, (240, 0, 159), 3)
	cv2.imshow("Contours", output)
	cv2.waitKey(0)

NameError: name 'cv2' is not defined